server:
  port: 80
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_film
    username: root
    password: type your db_password
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    
imagePath: type your path
username2: type your name
password: type your password